stages:
  preprocess:
    cmd: python src/data_preprocessing.py
    deps:
      - src/data_preprocessing.py
      - data/raw/
    outs:
      - data/processed/
    metrics:
      - metrics/preprocessing.json

  train:
    cmd: python src/train.py
    deps:
      - src/train.py
      - data/processed/
    outs:
      - models/checkpoints/best_model.pt

  evaluate:
    cmd: python src/evaluate.py
    deps:
      - src/evaluate.py
      - models/checkpoints/best_model.pt
      - data/processed/val/
    metrics:
      - metrics/eval.json

