global:
  scrape_interval: 15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets: ["lab3-alertmanager:9093"]

rule_files:
  - "alerts.yml"

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
        labels:
          app: "prometheus"
  - job_name: "node"
    static_configs:
      - targets: ["lab3-node-exporter:9100"]
        labels:
          app: "node"
  - job_name: "fastapi"
    static_configs:
      - targets: ["lab3-api-v1:8000"]
        labels:
          app: "fastapi"